name: clank
description: Clank rule simulator
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  test: ^1.16.8
dev_dependencies:
